Repository farmtedPlaydata/farmted-Repo, pull requests merged in 2023-11, with the labels that each got.

#15 Feature/#10 개별 경매 게시글 삭제 / 업데이트 구현 및 일부 수정
  board-service/src/main/java/com/farmted/boardservice/controller/BoardController.java
  board-service/src/main/java/com/farmted/boardservice/controller/api/SomethingApiController.java
  board-service/src/main/java/com/farmted/boardservice/domain/Board.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestCreateProductBoardDTO.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestUpdateProductBoardDTO.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetAuctionBoardDTO.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetAuctionBoardListDTO.java
  board-service/src/main/java/com/farmted/boardservice/enums/BoardType.java
  board-service/src/main/java/com/farmted/boardservice/enums/RoleEnums.java
  board-service/src/main/java/com/farmted/boardservice/exception/BoardTypeException.java
  board-service/src/main/java/com/farmted/boardservice/exception/RoleTypeException.java
  board-service/src/main/java/com/farmted/boardservice/exception/UpdateBoardException.java
  board-service/src/main/java/com/farmted/boardservice/feignClient/AuctionFeignClient.java
  board-service/src/main/java/com/farmted/boardservice/feignClient/ProductFeignClient.java
  board-service/src/main/java/com/farmted/boardservice/repository/BoardRepository.java
  board-service/src/main/java/com/farmted/boardservice/service/BoardService.java
  board-service/src/main/java/com/farmted/boardservice/vo/AuctionVo.java
  board-service/src/main/java/com/farmted/boardservice/vo/ProductVo.java
  board-service/src/test/java/com/farmted/boardservice/service/ServiceTest.java
Labels: 담당: 김태현, 도메인: 게시글

#20 [FEAT #17] Eureka-Service 구현
  eureka-service/.gitignore
  eureka-service/build.gradle
  eureka-service/gradle/wrapper/gradle-wrapper.jar
  eureka-service/gradle/wrapper/gradle-wrapper.properties
  eureka-service/gradlew
  eureka-service/gradlew.bat
  eureka-service/settings.gradle
  eureka-service/src/main/java/com/farmted/eurekaservice/EurekaServiceApplication.java
  eureka-service/src/main/resources/application.yml
  eureka-service/src/test/java/com/farmted/eurekaservice/EurekaServiceApplicationTests.java
Labels: 담당: 김태현, MSA 기틀

#27 Feature/#25 헤더 및 VO 전달 값 리팩토링
  product-service/src/main/java/com/farmted/productservice/controller/ProductController.java
  product-service/src/main/java/com/farmted/productservice/repository/ProductRepository.java
  product-service/src/main/java/com/farmted/productservice/service/ProductService.java
  product-service/src/main/resources/application.yml
Labels: 도메인:상품, 담당:김혜수

#30 Feature/#25 product-service 패인 통신을 위한 리펙토링 및 구체화
  product-service/build.gradle
  product-service/src/main/java/com/farmted/productservice/controller/ProductController.java
  product-service/src/main/java/com/farmted/productservice/dto/response/ProductResponseDto.java
  product-service/src/main/java/com/farmted/productservice/repository/ProductRepository.java
  product-service/src/main/java/com/farmted/productservice/service/ProductService.java
  product-service/src/main/resources/application.yml
Labels: 도메인:상품, 담당:김혜수, MSA 기틀

#32 [FEAT #31] Response Format 통일
  product-service/src/main/java/com/farmted/productservice/controller/ProductController.java
  product-service/src/main/java/com/farmted/productservice/util/GlobalResponseDto.java
Labels: documentation, 담당:김혜수, 담당:김태현

#40 [RESTORE /#36] 유레카 서비스 복구
  board-service/.gradle/8.0/executionHistory/executionHistory.bin
  board-service/.gradle/8.0/executionHistory/executionHistory.lock
  board-service/.gradle/8.0/fileHashes/fileHashes.bin
  board-service/.gradle/8.0/fileHashes/fileHashes.lock
  board-service/.gradle/8.0/fileHashes/resourceHashesCache.bin
  board-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  board-service/.gradle/buildOutputCleanup/outputFiles.bin
  board-service/.gradle/file-system.probe
  eureka-service/.gitignore
  eureka-service/.gradle/8.4/executionHistory/executionHistory.lock
  eureka-service/.gradle/8.4/fileHashes/fileHashes.lock
  eureka-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  eureka-service/.gradle/file-system.probe
  eureka-service/build.gradle
  eureka-service/gradle/wrapper/gradle-wrapper.jar
  eureka-service/gradle/wrapper/gradle-wrapper.properties
  eureka-service/gradlew
  eureka-service/gradlew.bat
  eureka-service/settings.gradle
  eureka-service/src/main/java/com/farmted/eurekaservice/EurekaServiceApplication.java
  eureka-service/src/main/resources/application.yml
  eureka-service/src/test/java/com/farmted/eurekaservice/EurekaServiceApplicationTests.java
  gateway-service/.idea/workspace.xml
Labels: 담당:김태현, MSA 기틀
