Repository farmtedPlaydata/farmted-Repo, pull requests merged in 2023-12, with the labels that each got.

#33 [FEAT #21 ] CommentService CRUD
  comment-service/.gitignore
  comment-service/build.gradle
  comment-service/gradle/wrapper/gradle-wrapper.jar
  comment-service/gradle/wrapper/gradle-wrapper.properties
  comment-service/gradlew
  comment-service/gradlew.bat
  comment-service/settings.gradle
  comment-service/src/main/java/com/farmted/commentservice/CommentServiceApplication.java
  comment-service/src/main/java/com/farmted/commentservice/controller/CommentController.java
  comment-service/src/main/java/com/farmted/commentservice/domain/Comment.java
  comment-service/src/main/java/com/farmted/commentservice/domain/TimeStamp.java
  comment-service/src/main/java/com/farmted/commentservice/dto/request/CommentCreateRequestDto.java
  comment-service/src/main/java/com/farmted/commentservice/dto/request/CommentUpdateRequestDto.java
  comment-service/src/main/java/com/farmted/commentservice/dto/response/CommentCreateResponseDto.java
  comment-service/src/main/java/com/farmted/commentservice/repository/CommentRepository.java
  comment-service/src/main/java/com/farmted/commentservice/service/CommentService.java
  comment-service/src/main/resources/application.yml
  comment-service/src/test/java/com/farmted/commentservice/CommentServiceApplicationTests.java
Labels: 담당:이찬혁, 도메인:댓글

#46 [Feature/#42] Board-Type별 퍼사드 패턴 구현 및 JPQL을 통한 레포지토리 최적화
  board-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  board-service/.gradle/buildOutputCleanup/outputFiles.bin
  board-service/.gradle/file-system.probe
  board-service/.idea/compiler.xml
  board-service/.idea/modules.xml
  board-service/build.gradle
  board-service/src/main/java/com/farmted/boardservice/BoardServiceApplication.java
  board-service/src/main/java/com/farmted/boardservice/config/EnumsConfig.java
  board-service/src/main/java/com/farmted/boardservice/config/enumConfig/RoleEnumsConverter.java
  board-service/src/main/java/com/farmted/boardservice/controller/BoardController.java
  board-service/src/main/java/com/farmted/boardservice/domain/Board.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestCreateBoardDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestUpdateProductBoardDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetCombinationDetailDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetCombinationListDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/detailDomain/ResponseGetAuctionDetailDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/detailDomain/ResponseGetBoardDetailDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/detailDomain/ResponseGetProductDetailDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/listDomain/ResponseGetAuctionDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/listDomain/ResponseGetBoardDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/listDomain/ResponseGetProductDto.java
  board-service/src/main/java/com/farmted/boardservice/enums/BoardType.java
  board-service/src/main/java/com/farmted/boardservice/feignClient/AuctionFeignClient.java
  board-service/src/main/java/com/farmted/boardservice/feignClient/MemberFeignClient.java
  board-service/src/main/java/com/farmted/boardservice/feignClient/ProductFeignClient.java
  board-service/src/main/java/com/farmted/boardservice/repository/BoardRepository.java
  board-service/src/main/java/com/farmted/boardservice/service/BoardService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/AuctionService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/MemberService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/ProductService.java
  board-service/src/main/java/com/farmted/boardservice/util/Board1PageCache.java
  board-service/src/main/java/com/farmted/boardservice/util/feignConverter/FeignConverter.java
  board-service/src/main/java/com/farmted/boardservice/vo/MemberVo.java
  board-service/src/main/java/com/farmted/boardservice/vo/ProductVo.java
  board-service/src/main/resources/application.yml
  board-service/src/test/java/com/farmted/boardservice/BoardServiceApplicationTests.java
  board-service/src/test/java/com/farmted/boardservice/demoTest/MockFeignTest.java
  board-service/src/test/java/com/farmted/boardservice/demoTest/SchedulerTest.java
  board-service/src/test/java/com/farmted/boardservice/repository/JPQLTest.java
  board-service/src/test/java/com/farmted/boardservice/service/BoardServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/ServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/AuctionServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/MemberServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/NoticeServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/ProductServiceTest.java
  board-service/src/test/resources/application-test.yml
Labels: 담당:김태현, 도메인:게시글

#54 Feature/#21 CommentService TestCode
  comment-service/org/junit/jupiter/api/annotations.xml
  comment-service/src/main/java/com/farmted/commentservice/controller/CommentController.java
  comment-service/src/main/java/com/farmted/commentservice/domain/Comment.java
  comment-service/src/main/java/com/farmted/commentservice/dto/request/CommentCreateRequestDto.java
  comment-service/src/main/java/com/farmted/commentservice/repository/CommentRepository.java
  comment-service/src/main/java/com/farmted/commentservice/service/CommentService.java
  comment-service/src/main/java/com/farmted/commentservice/util/InitDB.java
  comment-service/src/test/java/com/farmted/commentservice/service/CommentServiceTest.java
Labels: 담당:이찬혁, 도메인:댓글

#57 [CONFIG #56] 흰 화면만 나오는 기본 세팅
  board-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  board-service/.gradle/file-system.probe
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetCombinationListDto.java
  board-service/src/main/java/com/farmted/boardservice/exception/FeignException.java
  board-service/src/main/java/com/farmted/boardservice/repository/BoardRepository.java
  board-service/src/main/java/com/farmted/boardservice/service/BoardService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/AuctionService.java
  front-service/.babelrc
  front-service/.gitignore
  front-service/dist/bundle.js
  front-service/dist/bundle.js.LICENSE.txt
  front-service/package-lock.json
  front-service/package.json
  front-service/public/index.html
  front-service/src/App.tsx
  front-service/src/index.tsx
  front-service/tsconfig.json
  front-service/webpack.config.js
Labels: 담당:김태현, 프론트

#58 [Feature/#52] S3 인스턴스 생성, 이미지 업로드 구현, 테스트 코드, 테스트 코드 병렬 실행 완료
  board-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  board-service/.gradle/file-system.probe
  board-service/build.gradle
  board-service/src/main/java/com/farmted/boardservice/config/AwsS3Config.java
  board-service/src/main/java/com/farmted/boardservice/controller/BoardController.java
  board-service/src/main/java/com/farmted/boardservice/domain/Board.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestCreateBoardDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetCombinationListDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/detailDomain/ResponseGetAuctionDetailDto.java
  board-service/src/main/java/com/farmted/boardservice/enums/ExceptionType.java
  board-service/src/main/java/com/farmted/boardservice/facade/BoardFacade.java
  board-service/src/main/java/com/farmted/boardservice/service/BoardService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/AuctionService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/ImageService.java
  board-service/src/main/java/com/farmted/boardservice/service/subService/MemberService.java
  board-service/src/main/java/com/farmted/boardservice/util/CatchingFeign.java
  board-service/src/main/java/com/farmted/boardservice/vo/AuctionVo.java
  board-service/src/main/java/com/farmted/boardservice/vo/PagingInfo.java
  board-service/src/main/resources/application.yml
  board-service/src/test/java/com/farmted/boardservice/config/ImageUtils.java
  board-service/src/test/java/com/farmted/boardservice/config/InitDB.java
  board-service/src/test/java/com/farmted/boardservice/demoTest/MockFeignTest.java
  board-service/src/test/java/com/farmted/boardservice/demoTest/SchedulerTest.java
  board-service/src/test/java/com/farmted/boardservice/facade/BoardFacadeTest.java
  board-service/src/test/java/com/farmted/boardservice/repository/JPQLTest.java
  board-service/src/test/java/com/farmted/boardservice/service/BoardServiceBootTest.java
  board-service/src/test/java/com/farmted/boardservice/service/BoardServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/ServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/AuctionServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/ImageServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/MemberServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/NoticeServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/service/subService/ProductServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/util/SchedulerTest.java
  board-service/src/test/resources/application-testConfig.yml
  board-service/src/test/resources/images/testGif.gif
  board-service/src/test/resources/images/testJpg.jpg
  board-service/src/test/resources/images/testPng.png
  board-service/src/test/resources/junit-platform.properties
Labels: 담당:김태현, 도메인:게시글, MSA 기틀

#67 [FEAT #21] Member&Comment Feign
  comment-service/build.gradle
  comment-service/src/main/java/com/farmted/commentservice/CommentServiceApplication.java
  comment-service/src/main/java/com/farmted/commentservice/controller/CommentController.java
  comment-service/src/main/java/com/farmted/commentservice/domain/Comment.java
  comment-service/src/main/java/com/farmted/commentservice/dto/request/CommentCreateRequestDto.java
  comment-service/src/main/java/com/farmted/commentservice/feignclient/MemberFeignClient.java
  comment-service/src/main/java/com/farmted/commentservice/service/CommentService.java
  comment-service/src/main/java/com/farmted/commentservice/util/GlobalResponseDto.java
  comment-service/src/main/java/com/farmted/commentservice/util/InitDB.java
  comment-service/src/main/java/com/farmted/commentservice/vo/MemberVo.java
  comment-service/src/main/resources/application.yml
  front-service/package-lock.json
  front-service/package.json
  front-service/src/App.tsx
  front-service/src/icons/google-icon.svg
  front-service/src/icons/kakao-icon.svg
  front-service/src/login.js
  front-service/src/webpack.config.js
  package-lock.json
Labels: 담당:이찬혁

#69 [Fix/#68] 1차 종합 테스트 수정 및 Git Actions을 통한 CI 구축
  board-service/.github/workflows/test-board.yaml
  board-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  board-service/.gradle/file-system.probe
  board-service/.idea/compiler.xml
  board-service/.idea/dataSources.xml
  board-service/build.gradle
  board-service/src/main/java/com/farmted/boardservice/controller/BoardController.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestCreateBoardDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/request/RequestUpdateProductBoardDto.java
  board-service/src/main/java/com/farmted/boardservice/service/BoardService.java
  board-service/src/main/java/com/farmted/boardservice/util/JasyptConfig.java
  board-service/src/main/java/com/farmted/boardservice/vo/MemberVo.java
  board-service/src/main/java/com/farmted/boardservice/vo/ProductVo.java
  board-service/src/main/resources/application-enc.yml
  board-service/src/main/resources/application.yml
  board-service/src/test/java/com/farmted/boardservice/facade/BoardFacadeTest.java
  board-service/src/test/java/com/farmted/boardservice/service/BoardServiceTest.java
  board-service/src/test/java/com/farmted/boardservice/util/JasyptConfigTest.java
  board-service/src/test/resources/application-testConfig.yml
Labels: 담당:김태현, 도메인:게시글

#64 [FEAT #63] 게시글 리스트 틀 완성
  front-service/package-lock.json
  front-service/package.json
  front-service/src/App.tsx
  front-service/src/components/board/Board.tsx
  front-service/src/components/board/BoardBody.tsx
  front-service/src/components/board/boardDetail/BoardDetail.tsx
  front-service/src/components/board/boardHead/BoardHead.tsx
  front-service/src/components/board/boardList/BoardList.tsx
  front-service/src/components/board/boardList/boardItem/BoardItem.tsx
  front-service/src/index.tsx
Labels: 담당:김태현, 프론트

#73 [FEAT #72] 페이지네이션, FETCH, FRONT PROXY 구현
  board-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  board-service/.gradle/file-system.probe
  board-service/src/main/java/com/farmted/boardservice/controller/BoardController.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/ResponseGetCombinationListDto.java
  board-service/src/main/java/com/farmted/boardservice/vo/PagingInfo.java
  board-service/src/test/java/com/farmted/boardservice/service/BoardServiceBootTest.java
  front-service/package-lock.json
  front-service/package.json
  front-service/src/App.tsx
  front-service/src/components/Main.tsx
  front-service/src/components/board/Board.tsx
  front-service/src/components/board/BoardBody.tsx
  front-service/src/components/board/boardDetail/AuctionDetail.tsx
  front-service/src/components/board/boardDetail/BoardDetail.tsx
  front-service/src/components/board/boardDetail/ProductDetail.tsx
  front-service/src/components/board/boardHead/BoardHead.tsx
  front-service/src/components/board/boardHead/boardUtil/BoardType.tsx
  front-service/src/components/board/boardHead/boardUtil/BoardTypeSelector.tsx
  front-service/src/components/board/boardHead/boardUtil/CategoryList.tsx
  front-service/src/components/board/boardHead/boardUtil/EditorComponent.tsx
  front-service/src/components/board/boardHead/boardUtil/PageInfo.tsx
  front-service/src/components/board/boardHead/boardUtil/SearchBar.tsx
  front-service/src/components/board/boardHead/boardUtil/WriteButton.tsx
  front-service/src/components/board/boardList/BoardList.tsx
  front-service/src/components/board/boardList/boardItem/BoardItem.tsx
  front-service/src/components/board/boardRoute/BoardMain.tsx
  front-service/src/components/board/boardRoute/BoardRouteController.tsx
  front-service/src/components/board/createBoard/CreateBoard.tsx
  front-service/src/components/comment/Comment.tsx
  front-service/src/index.tsx
  front-service/src/webpack.config.js
  front-service/webpack.config.js
Labels: 담당:김태현, 프론트

#80 [FIX] DateTimeFormatter 일치화, 경매 상태 일치화 에러 수정
  auction-service/src/main/java/com/farmted/auctionservice/domain/Auction.java
  auction-service/src/main/java/com/farmted/auctionservice/dto/requestAuctionDto/AuctionCreateRequestDto.java
  auction-service/src/main/java/com/farmted/auctionservice/dto/responseAuctionDto/AuctionStatusResponseDto.java
  auction-service/src/main/java/com/farmted/auctionservice/observer/AuctionStatusChangeListener.java
  auction-service/src/main/resources/application.yml
  board-service/.gradle/file-system.probe
  front-service/src/components/bidding/BiddingForm.tsx
  product-service/src/main/java/com/farmted/productservice/Facade/ProductTypeFacade.java
  product-service/src/main/java/com/farmted/productservice/domain/Product.java
  product-service/src/main/java/com/farmted/productservice/dto/response/SaleAuctionTypeResponseDto.java
  product-service/src/main/java/com/farmted/productservice/dto/response/SaleProductTypeResponseDto.java
  product-service/src/main/java/com/farmted/productservice/enums/ProductType.java
  product-service/src/main/java/com/farmted/productservice/vo/ResponseAuctionGetVo.java
  product-service/src/main/resources/application.yml
Labels: bug, 담당:김혜수, TEST

#79 [CONFIG #78] Config 서버 구현 및 모든 서비스 암호화
  auction-service/build.gradle
  auction-service/src/main/java/com/farmted/auctionservice/util/JasyptConfig.java
  auction-service/src/main/resources/application.yml
  auction-service/src/main/resources/bootstrap.yml
  board-service/build.gradle
  board-service/src/main/resources/application.yml
  board-service/src/main/resources/bootstrap.yml
  comment-service/build.gradle
  comment-service/src/main/java/com/farmted/commentservice/domain/Comment.java
  comment-service/src/main/java/com/farmted/commentservice/dto/request/CommentCreateRequestDto.java
  comment-service/src/main/java/com/farmted/commentservice/util/InitDB.java
  comment-service/src/main/java/com/farmted/commentservice/util/JasyptConfig.java
  comment-service/src/main/resources/application.yml
  comment-service/src/main/resources/bootstrap.yml
  comment-service/src/test/java/com/farmted/commentservice/service/CommentServiceTest.java
  config-service/build.gradle
  config-service/src/main/java/com/farmted/configservice/ConfigServiceApplication.java
  config-service/src/main/resources/application.yml
  config-service/src/test/java/com/farmted/configservice/ConfigServiceApplicationTests.java
  member-service/build.gradle
  member-service/src/main/java/com/farmted/memberservice/config/AwsS3Config.java
  member-service/src/main/java/com/farmted/memberservice/util/JasyptConfig.java
  member-service/src/main/java/com/farmted/memberservice/util/ProfileManager.java
  member-service/src/main/resources/application.yml
  member-service/src/main/resources/bootstrap.yml
  pass-service/build.gradle
  pass-service/src/main/java/com/farmted/passservice/util/JasyptConfig.java
  pass-service/src/main/resources/application.yml
  pass-service/src/main/resources/bootstrap.yml
  product-service/build.gradle
  product-service/src/main/java/com/farmted/productservice/util/JasyptConfig.java
  product-service/src/main/resources/application.yml
  product-service/src/main/resources/bootstrap.yml
Labels: 담당:김태현, MSA 기틀

#74 [Feature/#21] 로그인 프론트 구현
  comment-service/.gitignore
  comment-service/src/main/java/com/farmted/commentservice/dto/request/CommentCreateRequestDto.java
  comment-service/src/main/java/com/farmted/commentservice/dto/response/CommentCreateResponseDto.java
  comment-service/src/main/resources/application-private.yml
  comment-service/src/main/resources/application.yml
  comment-service/src/test/java/com/farmted/commentservice/service/CommentServiceTest.java
  eureka-service/.gradle/8.4/checksums/checksums.lock
  eureka-service/.gradle/8.4/checksums/md5-checksums.bin
  eureka-service/.gradle/8.4/checksums/sha1-checksums.bin
  front-service/package-lock.json
  front-service/package.json
  front-service/public/icons/google-icon.png
  front-service/public/icons/kakaotalk-icon.png
  front-service/src/App.tsx
  front-service/src/Login.tsx
  front-service/src/icons/google-icon.svg
  front-service/src/icons/kakao-icon.svg
  front-service/src/login.js
  front-service/tsconfig.json
Labels: 담당:이찬혁, 프론트

#82 Feature/#76 입찰 신청 컴포넌트
  auction-service/src/main/java/com/farmted/auctionservice/controller/BiddingController.java
  auction-service/src/main/java/com/farmted/auctionservice/feignClient/AuctionToMemberFeignClient.java
  auction-service/src/main/java/com/farmted/auctionservice/observer/AuctionStatusChangeListener.java
  auction-service/src/main/java/com/farmted/auctionservice/repository/BiddingRepository.java
  auction-service/src/main/java/com/farmted/auctionservice/service/BiddingService.java
  front-service/package-lock.json
  front-service/package.json
  front-service/src/components/bidding/BiddingForm.tsx
  front-service/src/components/bidding/ModalComponent.tsx
  front-service/src/components/bidding/biddingList/BiddingListComponent.tsx
  front-service/src/components/bidding/biddingList/BiddingListStyled.tsx
  front-service/src/components/bidding/biddingList/biddingService.tsx
  front-service/src/components/bidding/biddingRouteController/BiddingRouteController.tsx
  front-service/src/components/board/boardDetail/AuctionDetail.tsx
  front-service/src/components/board/boardDetail/BoardDetail.tsx
  front-service/src/components/board/boardDetail/ProductDetail.tsx
  front-service/src/components/board/boardRoute/BoardRouteController.tsx
  front-service/src/components/board/createBoard/CreateBoard.tsx
  front-service/webpack.config.js
  gateway-service/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  gateway-service/.gradle/file-system.probe
  gateway-service/.idea/workspace.xml
  product-service/src/main/java/com/farmted/productservice/domain/Notification.java
  product-service/src/main/java/com/farmted/productservice/enums/NotificationType.java
Labels: 담당:김혜수, 프론트

#95 [FIX #102] 프론트 새로고침 가능 및 게이트웨이 호스트 수정
  auction-service/src/main/java/com/farmted/auctionservice/controller/AuctionController.java
  auction-service/src/main/java/com/farmted/auctionservice/controller/BiddingController.java
  board-service/Dockerfile
  board-service/src/main/java/com/farmted/boardservice/dto/response/detailDomain/ResponseGetBoardDetailDto.java
  board-service/src/main/java/com/farmted/boardservice/dto/response/listDomain/ResponseGetBoardDto.java
  front-service/dist/44e8eb94e877b3cabbe7.png
  front-service/dist/6120129f4ee375dbbb98.png
  front-service/dist/67cf3eeaef3348520a91.png
  front-service/dist/6efe8a83668cf421bd29.png
  front-service/dist/876cd9d1a1b0b8e4d241.png
  front-service/dist/8bd3f58086cc79037b60.png
  front-service/dist/951456d55230fe321b9a.png
  front-service/dist/bundle.js
  front-service/dist/bundle.js.LICENSE.txt
  front-service/package-lock.json
  front-service/package.json
  front-service/src/components/bidding/ModalComponent.tsx
  front-service/src/components/board/Board.tsx
  front-service/src/components/board/boardDetail/BoardDetail.tsx
  front-service/src/components/board/boardDetail/ProductDetail.tsx
  front-service/src/components/board/boardList/BoardList.tsx
  front-service/src/components/board/boardList/boardItem/BoardItem.tsx
  front-service/src/components/board/boardRoute/BoardMain.tsx
  front-service/src/components/board/boardRoute/BoardRouteController.tsx
  front-service/webpack.config.js
Labels: 담당:김태현
